### ISSUE TITLE
Error while opening js or css file

### ISSUE THREAD

**Issue by yusoofsh** [mthadley/linter-liferay#13]
![image](https://cloud.githubusercontent.com/assets/18055365/25603827/a45d71d2-2f29-11e7-88d0-2a9fef0eb053.png)

Atom version 1.17-beta4 x64
Linter version 2.1.4

**Comment by RawrBear** [comment]
Any fix for this?

**Comment by yusoofsh** [comment]
closed for not getting respond or the project is dead
